language: node_js
cache:
  directories:
    - node_modules
env:
  global:
    - SELENIUM_HOST=hub.browserstack.com
    - SELENIUM_PORT=80
    - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
    - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
    - BS_DEBUG=true
    - BS_LOCAL=true
    - secure: "PyLzTBZ6RcVJQsjqVxNQg3ODaTuCo5OvErbfhILaa0YslxxE7zY2hRmfvU1P3dlzkjgd7Ko13xbuU1ABrclBUxNArgzEhFnTTBcmM8+ujYCW1R8RQaQjWRj4+42xKfBsiDEADtXpE216q5bZ3gmccfD04pHsquvVsn+63yINR4CkZXoeJv/F0OqUzG1BjlP1gK/vL6jOVmlb5kDcsmwHq4FsvJAIQvkOhwvG3W5q0Rym+rJD+G3rJHIyUNRyhuMntYyYG4mdrVNkzuvbpXHc43R2aJNOGJoZUi6a3QhpvuACN3I8lcqHXgh0hy5hw7YukD8WPSByfQrRHsu120tkU8nyt3hY/uV03zt10CuCjNEK8cj6OEYtgnScyKrP9o/Ebo/K516e+CODy3/K1OMXUI5LBJuu1apS05rfeAwMrNJyHedy10Xst7o1DcN9ZUYRPmkjrmH2HMiyPEMlNwIXD5tfAX3PoWIfSupjwiFDZgIqAUYsFLaj8kDVtTMAbT2wVZg+muKu8/Aaq0qGPHcEBMiI5BbjiZcMnRVUZlIsm66JSyzrjU6Gn00dIXnc+F/N7mZRPZmoltJiwhNCSn/ool5BvEWFKRkxADYpYjbhixWMtG5GEg3+n2D3DLFtf4l4WQoNseNyTBYLte2NDwSBFTWJnvg4isCof5vLauSURgE="
    - secure: "iKR1fDDFj2apA4+RHGtNb2DF/+nidz63awQtHYZe7aHZ4PgGpMdKK1flgwGEySjy9gpRLSFv+/IRacKfyediYEN8PeFdcHaVZO4yxsa1Kc31dc3o81/4Kc9xgcn3KFamyqUCIIO1dHmqToFlRLVGLZKeCOSAHHxYdv6WeDE2mhR2vDQTjdZ+XU4YVG6Kp5TzAfNeM4Em3w34MZie7yvO/6/CalLU/KS+MYSgt3SvjTLsFc/GolgEP1z4XOrJzf2aW4BpuIqt1Gy0wsXgZPKnRblodPbZ9+AZWx89eVCkZ5BqLJvcMlOgKP/6eJuksUlU0Qjx4dDlywglhi5clkcmDpnJWflo33sE/TiIKswnPV69ucVUyHAmwUydivx5lNOxmZmj2fvy8YkMp6VRk42Kuo0WjkqCyiLDNjNfafPZqEMlKjsoy03zPe+ewF2w8rTm8ri20xp6DUhEBDCAsTqa7gskrlTVcaHGNNu9BE/cw8leaTpKDTCf0yLlA0d62JtoWugwsyT7IXMvjkkyNHzNZ+DeHO/wwncPH5Nezay1mrPD0HRs2VM3UAE0ivOoxfObU6WIt9oS32oMtrCjp1cC8+vC+2R1D7POxBKsa5yOdfNUwi3uIeTgfoTh4jZQONgwIF7VlqFION20HuG8+WzyElx7j9/OPlTSPEV5Po1tLb8="
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - ./BrowserStackLocal $BS_AUTHKEY localhost,3000,0 > /dev/null &
  - sleep 10
