language: node_js
cache:
  directories:
    - node_modules
addons:
  browserstack:
    username: "paigesaunders2"
    secure: "gHPEozq96Fqw/QTrSDAuP6Uvo9HXldJBcLttzzLYnNbYZ/SJndFF2gV8Kzw422WrXosvKU6j0ZxSEFX5AdkwR55UgimDnHw8HbTBWpRQAD0yG8q2ZKxNafa6eUGpS4zibN7Vy+cTLJlNd/qY02QnNAnodAif8ITyQTf0A+KiMDYno0cbpZsPsO7tZBHLSlYEgAgwaBJnjiuW1DU6IMhvxe4uDubQA5qzwLs2KVE2pL0NxbQcRJMQQSB7xHnoS2sxPstgOqbe9/1X76Oj+M+L0z28wCj9eNrrcclMra+DCIivl6Pqx5IkueEFnjPcDPsakBgZgU6gqBKBjZRqew5SE/sGQy1IDmCXDRDZQ0Qf7qtQ/RJPsyORzIS22iXgxZjHESzLPugIPXgbGHEYDRTm6I7DcAdQYEuBIySEPcuLPd5Vhe34vs3T2NyGq2Io/BL75t+JO4Vz6XZkTq406YUT2vZ51Eeq196eHqZGR4coCP/LoEQs84QqsRoFJj07mh6VOc6WgaNG4EzQIx6jCmrVAAMiBvk2has/qWN0yORezmJsj4cyUHh+MLPGKq4xzM3wbZq1Sn5GN5IBf+l3JqaXWgQEtWvcePoeWuaqtolo74d0nW/2tEdQhE7aw1taJGfmtdldvecvSNqImt7RfWKSI0OlCj8SOTcS2Vo160cY+Tw="
env:
  global:
    - SELENIUM_HOST=hub.browserstack.com
    - SELENIUM_PORT=80
    - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
    - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
    - BS_DEBUG=true
    - BS_LOCAL=true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - ./BrowserStackLocal $BS_AUTHKEY localhost,3000,0 > /dev/null &
  - sleep 10
